# 设置服务器端口
server:
  port: 8089
# docker run --name my-mysql -e MYSQL_ROOT_PASSWORD=root -d -p 33306:3306 mysql:latest
# docker run --name my-redis -d -p 6379:6379 redis:latest
spring:
  application:
    name: gudy_trade_gateway
# 网关id
# 这里不同的gateway进程需要设置不同的id和fetch-service-port
gateway:
  id: 1001
  fetch-service-port: 8890 # 排队机抓取服务的端口  和 sequence模块关联
  recv-port: 8091 # 和counter模块关联

